### ISSUE TITLE
No break statement

### ISSUE THREAD

**Issue by jimmychen7** [WeilonYing/cs3231-assignment-2#10]
https://github.com/WeilonYing/cs3231-assignment-2/blob/cbf7cfea1a61bf7df643ad569273acdabe2ce528/asst2-src/kern/arch/mips/syscall/syscall.c#L118-L121

No break statement on line 120.

**Comment by WeilonYing** [comment]
Fixed in c18ca5f6d6f85698fff19cdc871e238b4c78242d
